### ISSUE TITLE
Find out what version of FFMPEG is needed

### ISSUE THREAD

**Issue by cachemeoutside** [UCLALibrary/avalon#10]
Acceptance Criteria:
- [ ] Define version of FFMPEG needed for matterhorn / avalon

**Comment by darrowcoucla** [comment]
FFMPEG version 3.1

From the [single-server install notes](https://docs.library.ucla.edu/display/~darrowco/Avalon+v.+193)

"Version 3.1 is known to work."

You can also build a more modern ffmpeg from source, but not all versions work. Version 3.1 is known to work - check out the release/3.1 branch and build from there. If your modern ffmpeg uses fdk_aac instead of libfaac, adjust the Matterhorn etc/encoding/avalon.properties accordingly.

**Comment by cachemeoutside** [comment]
FFMPEG > 2.4. We'll be running 4.1 on production
